project:
  type: website

website:
  title: "digiskills"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-navigation: true

format:
  html:
    theme:
      - flatly
      - custom.scss
    css: styles.css
    toc: true

execute:
  freeze: auto
